CONFIG_ZMK_POINTING=y
CONFIG_ZMK_POINTING_SMOOTH_SCROLLING=y
CONFIG_ZMK_USB_BOOT=y
CONFIG_USB_HID_BOOT_PROTOCOL=y
CONFIG_ZMK_HID_INDICATORS=y
#CONFIG_ZMK_HID_REPORT_TYPE_NKRO=y
#CONFIG_ZMK_HID_KEYBOARD_REPORT_SIZE=24

CONFIG_INPUT_PINNACLE=y
CONFIG_RGBLED_WIDGET=y
CONFIG_RGBLED_WIDGET_SHOW_LAYER_CHANGE=y
#CONFIG_LOG=y
#CONFIG_LOG_PROCESS_THREAD_STARTUP_DELAY_MS=8000 


